apiVersion: v1
kind: PersistentVolume
metadata:
  name: fraud-benchmark-pv
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.23.181.60
    path: /fraud-benchmark
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
    - nconnect=8
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-benchmark-pvc
  namespace: fraud-det
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  volumeName: fraud-benchmark-pv
  storageClassName: ""
