apiVersion: v1
kind: PersistentVolume
metadata:
  name: fraud-benchmark-pv
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.storage.svc.cluster.local
    path: /financial-fraud-detection-demo
  mountOptions:
    - vers=3
    - tcp
    - hard
    - intr
    - noatime
    - nconnect=8
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-benchmark-pvc
  namespace: fraud-det
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  volumeName: fraud-benchmark-pv
  storageClassName: ""
